apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  containers:
  - name: rabbitmq
    image: rabbitmq:3-management
    ports:
    - containerPort: 5672
    - containerPort: 15672
    env:
    - name: RABBITMQ_DEFAULT_USER
      value: "guest"
    - name: RABBITMQ_DEFAULT_PASS
      value: "guest"
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
  - protocol: TCP
    port: 5672
    name: rabbitmq-port-1
    targetPort: 5672
  - protocol: TCP
    port: 15672
    name: rabbitmq-port-2
    targetPort: 15672
  type: NodePort
